from fastapi import FastAPI, HTTPException
from app.llm import LocalLLMConnector
from app.models.execute_sql_request import ExecuteRequest
from app.models.models_db_connector import PGDBConnector
from app.models.query_request import QueryRequest
from app.database_service import DatabaseService

app = FastAPI(title="LLM-DB CONNECTOR API", version="1.0.0")

llm = LocalLLMConnector(model_name="deepseek-r1", temperature=0.1)
db_service = DatabaseService()


@app.post("/connect_db")
def connect_db(config: PGDBConnector):
    """Connect once to the local or external database."""
    if not db_service.connect(config):
        raise HTTPException(status_code=400, detail="Failed to connect to database.")
    return {"connected": True}


@app.post("/generate_sql")
async def generate_sql(req: QueryRequest):
    """
    Generate SQL from a natural language instruction using the local LLM.
    This endpoint DOES NOT execute the SQL, it only returns it for review.
    """
    llm_response = llm.run(req.user_input)

    sql_code = llm_response.get("sql")
    explanation = llm_response.get("explanation")

    if not sql_code:
        raise HTTPException(status_code=400, detail="No SQL generated by LLM.")

    return {
        "generated_sql": sql_code,
        "explanation": explanation,
        "preview": "Review this SQL before execution.",
    }


@app.post("/disconnect_db")
def disconnect_db():
    """Close the local connection."""
    if db_service.disconnect():
        return {"disconnected": True}
    raise HTTPException(status_code=400, detail="No active connection to close.")


@app.post("/execute_sql")
def execute_sql(req: ExecuteRequest):
    """
    Execute a validated or user-approved SQL command on the connected database.
    """
    try:
        result = db_service.execute(req.sql)
        return {"executed_sql": req.sql, "result": result}
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
