from fastapi import FastAPI, HTTPException
from app.llm import LocalLLMConnector
from app.models.models_db_connector import PGDBConnector
from app.models.query_request import QueryRequest
from app.database_service import DatabaseService

app = FastAPI(title="LLM-DB CONNECTOR API", version="1.0.0")

llm = LocalLLMConnector(model_name="deepseek-r1", temperature=0.1)
db_service = DatabaseService()  


@app.post("/connect_db")
def connect_db(config: PGDBConnector):
    """Connect once to the local or external database."""
    if not db_service.connect(config):
        raise HTTPException(status_code=400, detail="Failed to connect to database.")
    return {"connected": True}


@app.post("/query")
async def handle_query(req: QueryRequest):
    """Generate SQL via LLM and execute on the local active connection."""
    llm_response = llm.run(req.user_input)
    sql_code = llm_response.get("sql")

    if not sql_code:
        raise HTTPException(status_code=400, detail="No SQL generated by LLM.")

    try:
        result = db_service.execute(sql_code)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return {
        "input": req.user_input,
        "generated_sql": sql_code,
        "explanation": llm_response.get("explanation"),
        "result": result,
    }


@app.post("/disconnect_db")
def disconnect_db():
    """Close the local connection."""
    if db_service.disconnect():
        return {"disconnected": True}
    raise HTTPException(status_code=400, detail="No active connection to close.")
